server:
  port: 8081

spring:
  application:
    name: ruoyi-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/learing-ruoyi?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&connectTimeout=300000&socketTimeout=300000
    username: root
    password: 123456
  data:
    redis:
      ## ??Redis??????????????0?15????0?
      database: 15
      ## Redis?????
      host: 127.0.0.1
      ## Redis?????
      port: 6379
      ## Redis???????????????ENC()?????
      password: 123456
      ## ??????????
      timeout: 0
      ## ?????
      jedis:
        pool:
          ## ???????????????????????? ???????????????????????
          max-active: 8
          ## ???????????????????????
          max-wait: -1
          ## ???????????
          max-idle: 8
          ## ???????????
          min-idle: 0
    # ?????????
  liquibase:
    # ????Liquibase?? true ?? false ??
    enabled: true
    # ??????????
    change-log: classpath:db/change_log/system/changelog-master.xml
    # ???????????
    database-change-log-lock-table: PLAN_DATABASECHANGELOGLOCK
    # ??????????
    database-change-log-table: PLAN_DATABASECHANGELOG

mybatis-plus:
  configuration:
    # MyBatis ??
    map-underscore-to-camel-case: true
    mapper-locations: classpath*:/mapper/**/*.xml
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #??sql??
  global-config:
    # ????
    db-config:
      # ?????
      id-type: ASSIGN_ID
      table-prefix: t_
      logic-delete-field: valid_tag
      logic-delete-value: '0'
      logic-not-delete-value: '1'
      table-underline: true


